### ISSUE TITLE
Create a organization for PTL and all addons

### ISSUE THREAD

**Issue by rafaelvieiras** [Lunatixz/XBMC_Addons#2]
Hello Luiz, how about creating an organization for all repositories related to PTL?

So it would be better to organize and better so that we can create a github page for the project with tutorials and others. And facilitates the cooperation of the community! What do you say?

I'm layout.

**Comment by Lunatixz** [comment]
xbmc_addons is a repository for kodi plugins and source, while ptvl skins, logos, and lists aren't... what kind of organization did you have in mind?

**Comment by rafaelvieiras** [comment]
In most add-ons in XBMC_Addons repository are aimed at PTL universe, aren't they?

In an organization can have multiple repositories and multiple users, helping to organize and collaborate.

Besides the fact that you can build the documentation for each repository, it is also possible to create the site for them and for the organization.

The organization's name would be "PseudoTV" and possess multiple repositories as
context.pseudotv.live.export, plugin.video.playonbrowser, plugin.video.ustvnow, repository.lunatixz, script.pseudo.library, script.pseudotv.lite, script.pseudotv.live, webinterface.ptvlmanager, etc ..

Then there could be the http://pseudotv.github.io website among other things. : D

The idea is to arrange everything in order to facilitate the collaboration of new developers with documentation besides setting up a website to lay install the add-ons and use.

https://help.github.com/articles/user-organization-and-project-pages/
https://help.github.com/articles/what-s-the-difference-between-user-and-organization-accounts/
Sorry About My English!

**Comment by Lunatixz** [comment]
Sounds interesting...
